// Ce fichier est généré automatiquement
// Ne le modifiez pas manuellement !
namespace Shnake;

public enum Sprite
{
    Props9,
    VillaYardFlowers1,
    VillaYardToyRocking1,
    Herbe19,
    Bucket1,
    Campfire1,
    VillaYardStomp1,
    Herbe18,
    Props8,
    Picnic4,
    VillaYardFlowers2,
    VillaYardToyRocking2,
    Bucket2,
    Campfire2,
    VillaYardStomp2,
    VillaYardToyRocking3,
    VillaYardFlowers3,
    Picnic5,
    Picnic1,
    VillaYardToyRocking7,
    WoodBoard3,
    Herbe22,
    Tree321,
    WoodBoard2,
    VillaYardToyRocking6,
    Picnic2,
    VillaYardToyRocking4,
    Herbe08,
    Herbe20,
    Panneau8,
    Herbe21,
    Herbe09,
    WoodBoard1,
    VillaYardToyRocking5,
    Picnic3,
    Bottle1,
    Rock3,
    Canard,
    Rock2,
    Bottle2,
    ModernUi,
    BenchedTable4,
    Rock1,
    Bottle3,
    FlowerBush7,
    Rock5,
    BenchedTable1,
    Fountain1,
    Sign8,
    Bottle6,
    Rock4,
    Rock6,
    Bottle4,
    BenchedTable2,
    Fountain2,
    BenchedTable3,
    Bottle5,
    Rock7,
    StreetLamp2,
    Sign6,
    PortableToilet1,
    Trash4,
    Flowers4,
    Banc4,
    SingleTrash1,
    Banc5,
    Flowers5,
    Trash5,
    Sign7,
    StreetLamp3,
    Rock9,
    StreetLamp1,
    Sign5,
    PortableToilet2,
    Chien,
    Banc7,
    SingleTrash2,
    SingleTrash3,
    Banc6,
    PortableToilet3,
    Sign4,
    Rock8,
    StreetLamp4,
    Moss2,
    Flowers2,
    Trash2,
    Banc2,
    Banc3,
    Trash3,
    Flowers3,
    Sign1,
    StreetLamp5,
    Sign3,
    PortableToilet4,
    Moss1,
    Trash1,
    Flowers1,
    SingleTrash4,
    Banc1,
    Sign2,
    Mushrooms2,
    VillaYardToyRocking8,
    Herbe04,
    Herbe10,
    Panneau4,
    Panneau5,
    Herbe11,
    Herbe05,
    Mushrooms3,
    Props1,
    Props3,
    Lapin,
    Mushrooms1,
    Herbe13,
    Herbe07,
    Panneau7,
    Panneau6,
    Herbe06,
    Herbe12,
    Props2,
    Props6,
    Mushrooms4,
    Barbecue3,
    Herbe16,
    Herbe02,
    Panneau2,
    Panneau3,
    Herbe03,
    Herbe17,
    Barbecue2,
    Mushrooms5,
    Props7,
    Props5,
    Personnage,
    Herbe01,
    Herbe15,
    Panneau1,
    Herbe14,
    Barbecue1,
    Mushrooms6,
    Props4,

}

public enum SoundEffect
{
    UiPuzzleGame9,
    UiPuzzleGame8,
    UiButtonEnable,
    UiSwish1,
    UiSwish2,
    UiButtonClick2,
    UiKeypad4,
    UiKeypad5,
    UiButtonClick3,
    UiButtonClick1,
    UiButtonClick4,
    UiKeypad2,
    UiKeypad3,
    UiButtonClick5,
    UiButtonClick7,
    UiKeypad1,
    UiPuzzleGame10,
    UiButtonClick6,
    UiKeypadPrompt,
    UiButtonClick8,
    UiButtonClick9,
    UiKeypadConfirmed,
    UiPuzzleGame3,
    UiPuzzleGame2,
    UiPuzzleGame1,
    UiKeypadRejected,
    UiPuzzleGame5,
    UiMenuOpen,
    UiPuzzleGame4,
    UiPuzzleGame6,
    UiKeypadError,
    UiPuzzleGame7,

}

public enum Musique
{
    MusicMagicalForest,
    MusicChickenParty,

}

public static class AssetExtensions
{
    public static string GetPath(this Sprite sprite)
    {
        return "Assets/" + sprite.ToString() + ".png";
    }

    public static string GetPath(this SoundEffect sound)
    {
        return "Assets/" + sound.ToString() + ".ogg";
    }

    public static string GetPath(this Musique sound)
    {
        return "Assets/" + sound.ToString() + ".ogg";
    }
}
